name: markdown_tooltip
description: "A tooltip supporting markdown and default delayed popup to avoid clutter."
version: 0.0.6
homepage: https://github.com/gjwgit/markdown_tooltip

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

# To automatically upgrade package dependencies:
#
# `flutter pub upgrade --major-versions`.
#
# To see which dependencies have newer versions available:
#
# `flutter pub outdated`

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#   # The original `dart-code-metrics` is end-of live and has migrated
#   # to a paid service. This fork maintains it's compatibility with the
#   # latest flutter but is not otherwise maintained or updated.

#   dart_code_metrics:
#     git:
#       url: https://github.com/anusii/dart-code-metrics.git
#       ref: dev

# dependency_overrides:
#   # Required for dart-code-metrics.
#   collection: ^1.19.0

flutter:
